application: groupon2334
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /
  script: helloworld.py

- url: /rpc
  script: rpc/handler.py

- url: /testonly
  script: helloworld.py

- url: /update_progress
  script: status.py

- url: /cron/update_sites
  script: cron_jobs.py
