application: tuanadminsite
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /
  script: helloworld.py

- url: /rpc
  script: rpchandler.py

- url: /datastore/.*
  script: datastore.py
  login: admin

- url: /update/.*
  script: updateadmin.py
